### ISSUE TITLE
More Mixed Indentations

### ISSUE THREAD

**Issue by BrandonGroth** [tdecker91/Card3D#3]
The following files have mixed indentations:

1. addons/card_3d/scripts/card_3d.gd
2. addons/card_3d/scripts/card_collection_3d.gd
3. addons/card_3d/scripts/card_layouts/card_layout.gd
4. addons/card_3d/scripts/card_layouts/fan_card_layout.gd
5. addons/card_3d/scripts/card_layouts/line_card_layout.gd
6. addons/card_3d/scripts/card_layouts/pile_card_layout.gd
7. addons/card_3d/scripts/drag_controller.gd
8. example/face_card_3d.gd
9. example_battle/scripts/battle_cards.gd

I have fixed them in a local branch, but I doubt I have push permissions to this repo.

**Comment by tdecker91** [comment]
@BrandonGroth Thanks, 
I will convert those to tabbed indentation. But you can fork the repo and push to a branch and then open a PR if I don't get around to this soon.
