### ISSUE TITLE
can't find it in the godot asset library [godot 4.3]

### ISSUE THREAD

**Issue by ramonskie** [tdecker91/Card3D#6]
i tried to load this project from the asset library. 
but it can't be found

version: godot 4.3
platform: linux

i know we can easily download and copy the content.
but just wanted to let you know the current install instructions do not work as intended

**Comment by tdecker91** [comment]
@ramonskie 

I'm sorry you're having trouble downloading this from the godot asset library.

I double checked and I have the correct commit hash (`1fbe62520b86a35cbd189a1e2c8423cb4ee26227`) on the godot asset page. Installing from the godot asset library worked as expected for me. 

Could there be something else I'm forgetting?

**Comment by ramonskie** [comment]
![image](https://github.com/user-attachments/assets/d2ae188d-8710-4d27-9c79-72032f45399b)
within the support menu i selected `[featured,community, testing]`
tried it with godot version `4.3` and `4.2.2`

maby im doing something wrong as this is my first time actually really playing with godot.

**Comment by tdecker91** [comment]
@ramonskie 
I see now. 

It looks like you're trying to import "templates, projects, and demos" from the godot launcher.

Card3D is an asset and must be imported from an existing project. Create a new projects, then under "AssetLib" you can search assets. Card3D and several other card assets should show up in the search. 

I can add wording to the readme to hopefully clear that up.

**Comment by ramonskie** [comment]
i feel so stupid.... this works
and i thank you for your time
